Repository dvsa/cvs-svc-test-types, pull requests merged in 2023-03, with the labels that each got.

#173 fix(cb2-7633): ability to send multiple vehicleSubclasses (#172)
  src/functions/getTestTypesById.ts
  src/models/ITestType.ts
  src/services/TestTypesService.ts
  tests/integration/getTestTypesByIdFunction.intTest.ts
  tests/resources/test-types.json
  tests/unit/testTypesService.unitTest.ts
Labels: bug, enhancement

#174 feat(cb2-7727): remove the small trailer type
  docs/test-types-api.yml
  package-lock.json
  package.json
  patches/dynamodb-localhost+0.0.9.patch
  src/models/ITestType.ts
  tests/resources/test-types.json
Labels: bug

#179 feat(cb2-7765): specify eu vehicle category for trl test types
  src/models/ITestType.ts
  tests/resources/test-types.json
Labels: enhancement

#180 fix(cb2-7765): fix the parent test types for small trailers
  tests/resources/test-types.json
Labels: bug

#182 feat(cb2-7846): add the nft test type for trailers
  tests/resources/test-types.json
Labels: enhancement
